import {storageService} from './storageService.js'
import {makeId} from './utilService.js'

export const beerService = {
	query,
	save,
	remove,
	getById,
	getEmptyBeer,
	tryBeer,
}

const STORAGE_KEY = 'beers'

const gDefaultBeers = [
	{
		'_id': 'rfhssdfhdsfgh5rt1',
		'gate': '',
		'brewery': 'Mikkeller',
		'beerName': 'Iskold',
		'type': 'Vienna lager',
		'abv': 5.6,
		'ibu': 0,
		'untapped': 3.36,
		'price': 15,
		'cost': '',
		'supplier': 'Hacerem',
	},
	{
		'_id': 'rsthwtrjhw6utrjw5j2',
		'gate': 'b6',
		'brewery': 'BeaverTown',
		'beerName': 'Solar Flame',
		'type': 'Hazy DIPA',
		'abv': 8,
		'ibu': 0,
		'untapped': 3.72,
		'price': 33,
		'supplier': 'Redax',
		'cost': 19,
	},
	{
		'_id': '45ewtrfdgbgndfhgjedjkhker3',
		'gate': 'b7',
		'brewery': 'BeaverTown',
		'beerName': 'Supermoon',
		'type': 'Hazy IPA',
		'abv': 6,
		'ibu': 0,
		'untapped': 3.61,
		'price': 33,
		'cost': 19,
	},
	{
		'_id': 'r4yjdtymetywesymtd,mdju,',
		'gate': '',
		'brewery': 'Mikkeller',
		'beerName': 'Beer geek cocoa shake',
		'type': 'Imperial Stout',
		'abv': 12.1,
		'ibu': 0,
		'untapped': 4.11,
		'price': 37,
	},
	{
		'_id': 'rtyekmuy,eu,eyyj,ydu,6',
		'gate': 'd8',
		'brewery': 'BrewDog',
		'beerName': 'Double punk',
		'type': 'DIPA',
		'abv': 8.2,
		'ibu': 60,
		'untapped': 3.71,
		'price': 22,
		'cost': 12.21,
	},
	{
		'_id': 'rirylrl,eru,7',
		'gate': '',
		'brewery': 'Kasteel',
		'beerName': 'Bacchus',
		'type': '',
		'abv': '',
		'ibu': '',
		'untapped': '',
		'price': 15,
	},
	{
		'_id': 'rrulekdtukri8',
		'gate': '',
		'brewery': 'Mikkeller',
		'beerName': 'HOD Syrax',
		'type': 'Session IPA',
		'abv': 3.5,
		'ibu': 0,
		'untapped': 3.44,
		'price': 20,
		'supplier': 'Hacerem',
		'cost': 11.22,
	},
	{
		'_id': 'rruyl479;i;lfgydd9',
		'gate': 'e1',
		'brewery': 'Mikkeller',
		'beerName': 'Japanese',
		'type': 'Rice Lager',
		'abv': 5.1,
		'ibu': 0,
		'untapped': 3.33,
		'price': 16,
		'supplier': 'Hacerem',
		'cost': 8.91,
	},
	{
		'_id': 'r1tfy8lto;klcg0',
		'gate': 'b1',
		'brewery': 'Kasteel',
		'beerName': 'Shoshan',
		'type': 'Spiced',
		'abv': 4.7,
		'ibu': 0,
		'untapped': 3.2,
		'price': 15,
		'cost': 7.5,
		'supplier': 'Redax',
	},
	{
		'_id': 'rdgh5dfgh555klcg0',
		'gate': 'a4',
		'brewery': 'Mikkeller',
		'beerName': 'Peter Pale and mary',
		'type': 'Gluten free Pale Ale',
		'abv': 4.6,
		'ibu': 0,
		'untapped': 3.6,
		'price': 15,
		'cost': 7.59,
	},
	{
		'_id': 'r1fgj.rl.vff2',
		'gate': 'd2',
		'brewery': 'BrewDog',
		'beerName': 'Basic Shake',
		'type': 'Milkshake IPA',
		'abv': 4.7,
		'ibu': 20,
		'untapped': 3.48,
		'price': 15,
		'cost': 7.59,
		'supplier': 'Hacerem',
	},
	{
		'_id': 'r1uiafhg4',
		'gate': '',
		'brewery': 'BrewDog',
		'beerName': 'Pupet Master',
		'type': 'West coast IPA',
		'abv': 6.5,
		'ibu': 50,
		'untapped': 3.6,
		'price': 21,
		'cost': 11.88,
		'supplier': 'Hacerem',
	},
	{
		'_id': 'rkjldsaghLKDG15',
		'gate': '',
		'brewery': 'BrewDog',
		'beerName': 'Custom Shop',
		'type': 'NEIPA',
		'abv': 8,
		'ibu': 0,
		'untapped': 3.73,
		'price': 16,
	},
	{
		'_id': 'r1FJDFBGHLKJA6',
		'gate': '',
		'brewery': 'BrewDog',
		'beerName': 'Lost Guava',
		'type': 'Lager',
		'abv': 4.5,
		'ibu': 20,
		'untapped': 3.42,
		'price': 15,
		'cost': 7.92,
		'supplier': 'Hacerem',
	},
	{
		'_id': 'rFKLDFJHGV17',
		'gate': '',
		'brewery': 'BrewDog',
		'beerName': 'Lost lyhee&lime',
		'type': 'Lager',
		'abv': 4.5,
		'ibu': 20,
		'untapped': 3.32,
		'price': 15,
		'supplier': 'Hacerem',
		'cost': 7.92,
	},
	{
		'_id': 'r1AHGNJSH8',
		'gate': '',
		'brewery': 'BrewDog',
		'beerName': 'Lost Blood orange',
		'type': 'Lager',
		'abv': 4.5,
		'ibu': 20,
		'untapped': 3.35,
		'price': 15,
		'cost': 7.92,
		'supplier': 'Hacerem',
	},
	{
		'_id': 'rghsfms19',
		'gate': 'b5',
		'brewery': 'BeaverTown',
		'beerName': 'Bloody hell',
		'type': 'Blood Orange IPA',
		'abv': 5.5,
		'ibu': 40,
		'untapped': 3.7,
		'price': 19,
		'supplier': 'Redax',
		'cost': 11,
	},
	{
		'_id': 'rjhlfjs20',
		'gate': 'b2',
		'brewery': 'BeaverTown',
		'beerName': 'Gamma ray',
		'type': 'APA',
		'abv': 5.4,
		'ibu': 45,
		'untapped': 3.75,
		'price': 19,
		'cost': 11,
		'supplier': 'Redax',
	},
	{
		'_id': 'r2atjsykmwuk1',
		'gate': 'b3',
		'brewery': 'BeaverTown',
		'beerName': 'Neck oil',
		'type': 'Session IPA',
		'abv': 4.3,
		'ibu': 31,
		'untapped': 3.65,
		'price': 19,
		'cost': 11,
		'supplier': 'Redax',
	},
	{
		'_id': 'r2syhkystuk,lsws2',
		'gate': 'b4',
		'brewery': 'BeaverTown',
		'beerName': 'Lupuloid',
		'type': 'IPA',
		'abv': 6.7,
		'ibu': 65,
		'untapped': 3.8,
		'price': 19,
		'cost': 11,
		'supplier': 'Redax',
	},
	{
		'_id': 'r2stykmeyu,leyil,s3',
		'gate': 'c4',
		'brewery': 'Siren',
		'beerName': 'Calypso',
		'type': 'Sour',
		'abv': 4,
		'ibu': 26,
		'untapped': 3.51,
		'price': 19,
		'cost': 11,
	},
	{
		'_id': 'r2artjajwykatrh4',
		'gate': 'c6',
		'brewery': 'Siren',
		'beerName': 'Broken Dream',
		'type': 'Oatmeal stout',
		'abv': 6.5,
		'ibu': 0,
		'untapped': 3.83,
		'price': 19,
		'cost': 11,
	},
	{
		'_id': 'r2aetjhatjqrtyjrya5',
		'gate': 'c7',
		'brewery': 'Siren',
		'beerName': 'Lumina',
		'type': 'Session IPA',
		'abv': 4.2,
		'ibu': 0,
		'untapped': 3.6,
		'price': 19,
		'cost': 11,
	},
	{
		'_id': 'ratjatjaqrtjartqj26',
		'gate': 'c8',
		'brewery': 'Siren',
		'beerName': 'Yu LU',
		'type': 'SEssion IPA',
		'abv': 3.6,
		'ibu': 0,
		'untapped': 3.47,
		'price': 19,
		'cost': 11,
	},
	{
		'_id': 'r2atrjaryjryjk7',
		'gate': 'c9',
		'brewery': 'Siren',
		'beerName': 'Santo',
		'type': 'DH Lager',
		'abv': 5,
		'ibu': 0,
		'untapped': 3.58,
		'price': 19,
		'cost': 11,
	},
	{
		'_id': 'r2rtjsywktwykwyk8',
		'gate': '',
		'brewery': 'BrewDog',
		'beerName': 'Hazy Jane Peach',
		'type': 'NEIPA',
		'abv': 5,
		'ibu': 0,
		'untapped': 3.61,
		'price': 15,
		'supplier': 'Hacerem',
		'cost': 6.93,
	},
	{
		'_id': 'r2ywjksywkwyk9',
		'gate': 'd3',
		'brewery': 'BrewDog',
		'beerName': 'Hop Tiger',
		'type': 'NEIPA',
		'abv': 7.5,
		'ibu': 0,
		'untapped': 3.75,
		'price': 15,
		'cost': 8.58,
		'supplier': 'Hacerem',
	},
	{
		'_id': 'r3wykwyktwykwyk0',
		'gate': 'd7',
		'brewery': 'BrewDog',
		'beerName': 'Hazy Jane Guava ',
		'type': 'NEIPA',
		'abv': 5,
		'ibu': 20,
		'untapped': 3.73,
		'price': 15,
		'supplier': 'Hacerem',
		'cost': 6.93,
	},
	{
		'_id': 'r3ywktuktukrwja1',
		'gate': '',
		'brewery': 'BeaverTown',
		'beerName': 'BeaverTown',
		'type': 'Hazy IPA',
		'abv': 6.5,
		'ibu': 0,
		'untapped': 3.66,
		'price': 33,
	},
	{
		'_id': 'rWU6WYUJWTRHYQWT32',
		'gate': 'b9',
		'brewery': 'BeaverTown',
		'beerName': 'Space Hulk',
		'type': 'NEIPA',
		'abv': 6,
		'ibu': 0,
		'untapped': 3.63,
		'price': 33,
		'cost': 19,
	},
	{
		'_id': 'r3RYERYEYHERTHE4',
		'gate': '',
		'brewery': 'Siren',
		'beerName': 'Castillien',
		'type': 'Juicy Sour IPA',
		'abv': 6.2,
		'ibu': 0,
		'untapped': 3.68,
		'price': 33,
		'cost': 19,
		'supplier': 'Redax',
	},
	{
		'_id': 'r35RETURTURTHE',
		'gate': '',
		'brewery': 'BeaverTown',
		'beerName': 'Tropigamma',
		'type': 'Tropical IPA',
		'abv': 7,
		'ibu': 60,
		'untapped': 3.94,
		'price': 22,
		'supplier': 'Redax',
		'cost': 12.5,
	},
	{
		'_id': 'r3DFGJRDJDJ6',
		'gate': 'c3',
		'brewery': 'Siren',
		'beerName': 'Futurist',
		'type': 'Gluten free Session IPA',
		'abv': 4.8,
		'ibu': 0,
		'untapped': 3.92,
		'price': 28,
		'cost': 16,
	},
	{
		'_id': 'r3GFDFGHJDHJ7',
		'gate': 'd1',
		'brewery': 'BrewDog',
		'beerName': '90 Days Bock',
		'type': 'Amplified Lager',
		'abv': 8,
		'ibu': 0,
		'untapped': 3.55,
		'price': 15,
		'cost': 8.25,
		'supplier': 'Hacerem',
	},
	{
		'_id': 'r38GFJRSYJKSYKJ',
		'gate': 'd5',
		'brewery': 'BrewDog',
		'beerName': '5AM Saint',
		'type': 'American Red ale',
		'abv': 5,
		'ibu': 30,
		'untapped': 3.63,
		'price': 14,
		'supplier': 'Hacerem',
		'cost': 7.59,
	},
	{
		'_id': 'rSRYKSYJSRYJ39',
		'gate': '',
		'brewery': 'BrewDog',
		'beerName': 'Urban Fog',
		'type': 'NEIPA',
		'abv': 6.5,
		'ibu': 0,
		'untapped': 3.74,
		'price': 23,
		'supplier': 'Hacerem',
		'cost': '',
	},
	{
		'_id': 'r4SRTJSRTJSRTYJ0',
		'gate': '',
		'brewery': 'BrewDog',
		'beerName': 'Candy Kittens',
		'type': 'NEIPA',
		'abv': 6,
		'ibu': 29,
		'untapped': 3.09,
		'price': 23,
		'supplier': 'Hacerem',
		'cost': 13.2,
	},
	{
		'_id': 'r4DRTYJSRTJSRTYJRYSJ1',
		'gate': '',
		'brewery': 'BrewDog',
		'beerName': 'Way out West',
		'type': 'West cost IPA',
		'abv': 6.5,
		'ibu': 40,
		'untapped': 3.59,
		'price': 23,
		'supplier': 'Hacerem',
		'cost': 13.2,
	},
	{
		'_id': 'r4YDRJDTYJDYRJDYTJ2',
		'gate': '',
		'brewery': 'BrewDog',
		'beerName': 'Almost Famous',
		'type': 'NEIPA',
		'abv': 6.8,
		'ibu': 0,
		'untapped': 3.75,
		'price': 23,
		'supplier': 'Hacerem',
		'cost': 13.2,
	},
	{
		'_id': 'rSRYJSYRJYTJ43',
		'gate': 'e7',
		'brewery': 'Kasteel',
		'beerName': 'Nitro Rouge',
		'type': 'Friut Beer',
		'abv': 7,
		'ibu': 8,
		'untapped': 3.4,
		'price': 17,
		'cost': 9.8,
	},
	{
		'_id': 'r44SRTJSRTYJRYJ',
		'gate': 'e8',
		'brewery': 'Kasteel',
		'beerName': 'Nitro Quad',
		'type': 'Belgian Quad',
		'abv': 11,
		'ibu': 0,
		'untapped': 3.67,
		'price': 17,
		'cost': 9.8,
	},
	{
		'_id': 'rSRTJYRJRYJSRTYJ45',
		'gate': 'e9',
		'brewery': 'Kasteel',
		'beerName': 'Nitro Noir',
		'type': 'Porter',
		'abv': 5.7,
		'ibu': 0,
		'untapped': 3.32,
		'price': 17,
		'cost': 9.8,
	},
	{
		'gate': 'a1',
		'brewery': 'Thornbridge',
		'beerName': 'Quiet Storm Cashmere',
		'type': 'APA',
		'abv': 5.5,
		'ibu': '',
		'untapped': 3.69,
		'price': 22,
		'cost': 11.25,
		'_id': 'GQYz0kPX08gjrBt',
	},
	{
		'gate': 'a2',
		'brewery': 'Thornbridge',
		'beerName': 'McConnels',
		'type': 'Stout ',
		'abv': 5,
		'ibu': 30,
		'untapped': 3.6,
		'price': 22,
		'cost': 12.5,
		'_id': 'efhF37DBWrA45zB',
	},
	{
		'gate': 'a3',
		'brewery': 'Thornbridge',
		'beerName': 'Chiron',
		'type': 'APA',
		'abv': 5,
		'ibu': 36,
		'untapped': 3.62,
		'price': 17,
		'cost': 9.6,
		'_id': 'KUQx1wcQ0U4ExV6',
	},
	{
		'gate': 'a5',
		'brewery': 'Mikkeller',
		'beerName': 'Kaerlek',
		'type': 'Hazy pale ale',
		'abv': 4.9,
		'ibu': '',
		'untapped': 3.49,
		'price': 15,
		'supplier': 'Hacerem',
		'cost': 8.25,
		'_id': 'Nl4aqUr6nsxu7oD',
	},
	{
		'gate': 'a6',
		'brewery': 'Siren',
		'beerName': 'Supersonic',
		'type': 'DIPA ',
		'abv': 8.5,
		'ibu': '',
		'untapped': 4.07,
		'price': 38,
		'cost': 22,
		'_id': 'GNcFyeKXokrapGu',
	},
	{
		'gate': 'a7',
		'brewery': 'Mikkeller',
		'beerName': 'Viking Shake',
		'type': 'Imperial Stout',
		'abv': 13,
		'ibu': '',
		'untapped': 4.15,
		'price': 35,
		'supplier': 'Hacerem',
		'cost': 19.8,
		'_id': 'cDEoADyMxeNy6Nv',
	},
	{
		'gate': 'a8',
		'brewery': 'Lervig',
		'beerName': 'Lucky Jack Grapfruit P',
		'type': 'Pale Ale',
		'abv': 4.7,
		'ibu': 45,
		'untapped': 3.47,
		'price': 19,
		'cost': 11,
		'_id': 'jmVog6DfdrUXfpx',
	},
	{
		'gate': 'a9',
		'brewery': 'Lervig',
		'beerName': 'Lucky Jack Mango ',
		'type': 'Pale Ale',
		'abv': 4.7,
		'ibu': '',
		'untapped': 3.36,
		'price': 19,
		'cost': 19,
		'_id': 'uYYKWxFT6NU6ozI',
	},
	{
		'gate': 'b8',
		'brewery': 'BeaverTown',
		'beerName': 'Heavy Gravity',
		'type': 'Hazy IPA ',
		'abv': 6.5,
		'ibu': '',
		'untapped': 3.66,
		'price': 33,
		'supplier': 'Redax',
		'cost': 19,
		'_id': 'G9pmiAZBEzuMuBI',
	},
	{
		'gate': 'c1',
		'brewery': 'Siren',
		'beerName': 'Hard Pour Broken Dream',
		'type': 'Stout Oatmeal',
		'abv': 6.5,
		'ibu': '',
		'untapped': 3.9,
		'price': 32,
		'supplier': 'Redax',
		'cost': 18,
		'_id': 'x1IZNon3mKeKQhY',
	},
	{
		'gate': 'c2',
		'brewery': 'Siren',
		'beerName': 'Thought Bubble ',
		'type': 'Juicy IPA',
		'abv': 6,
		'ibu': '',
		'untapped': 3.63,
		'price': 32,
		'supplier': 'Redax',
		'cost': 18,
		'_id': 'Gpu4Bs9vVSMUq8G',
	},
	{
		'gate': 'c5',
		'brewery': 'Siren',
		'beerName': 'Soundwave',
		'type': 'IPA',
		'abv': 5.6,
		'ibu': '',
		'untapped': 3.73,
		'price': 19,
		'supplier': 'Redax',
		'cost': 11,
		'_id': 'KHS5B5ZEVe6YTdZ',
	},
	{
		'gate': 'd4',
		'brewery': 'BrewDog',
		'beerName': 'Triple Agent',
		'type': 'Oak aged triple ',
		'abv': 8.5,
		'ibu': '',
		'untapped': 3.63,
		'price': 15,
		'cost': 8.25,
		'supplier': 'Hacerem',
		'_id': 'S4kq2wgukija287',
	},
	{
		'gate': 'd6',
		'brewery': 'BrewDog',
		'beerName': 'Sand Man',
		'type': 'Belgian IPA',
		'abv': 6.5,
		'ibu': '',
		'untapped': 3.59,
		'price': 15,
		'cost': 8.58,
		'supplier': 'Hacerem',
		'_id': '25kKcl4XecWshoF',
	},
	{
		'gate': 'd9',
		'brewery': 'BrewDog',
		'beerName': 'Silk Road',
		'type': 'Hazy IPA',
		'abv': 6.5,
		'ibu': 11,
		'untapped': 3.7,
		'price': 14,
		'cost': 7.59,
		'supplier': 'Hacerem',
		'_id': 'mj8ct6Cm0kCblhg',
	},
	{
		'gate': 'e2',
		'brewery': 'Thornbridge',
		'beerName': 'Shelby',
		'type': 'IPA',
		'abv': 5,
		'ibu': 35,
		'untapped': 3.27,
		'price': 15,
		'cost': 8.16,
		'_id': 'jeOkIIxXyXLSejO',
	},
	{
		'gate': 'e3',
		'brewery': 'Horizont',
		'beerName': 'Hazy Queen ',
		'type': 'NEIPA ',
		'abv': 6,
		'ibu': 45,
		'untapped': 3,
		'price': 18,
		'cost': 10.08,
		'_id': 'WU0ZBLInIEJM6lz',
	},
	{
		'gate': 'e4',
		'brewery': 'Horizont',
		'beerName': 'Traveling Monkey Time Warp ',
		'type': 'NEIPA ',
		'abv': 7,
		'ibu': '',
		'untapped': 3.88,
		'price': 28,
		'cost': 15.84,
		'_id': 'yzA0oCpBUosoNIy',
	},
	{
		'gate': 'e5',
		'brewery': 'Horizont',
		'beerName': 'Selfish Games Milk Stout with Tonka Beans',
		'type': 'Stout - Milk ',
		'abv': 6.8,
		'ibu': '',
		'untapped': 3.81,
		'price': 28,
		'cost': 15.84,
		'_id': 'I843IbZOUAxcRNL',
	},
	{
		'gate': 'e6',
		'brewery': 'Horizont',
		'beerName': 'Juniper & Juice Sour Ale',
		'type': 'Sour',
		'abv': 4,
		'ibu': 12,
		'untapped': 3.68,
		'price': 28,
		'cost': 15.84,
		'_id': 'oSFEC8KKVYyiUAe',
	},
	{
		'gate': '',
		'brewery': 'BrewDog',
		'beerName': 'Tonys Hopolonely ',
		'type': 'Milkshake IPA ',
		'abv': 6.3,
		'ibu': 20,
		'untapped': 3.41,
		'price': 17,
		'cost': 9.9,
		'supplier': 'Hacerem',
		'_id': 'HffYNxOa3ANzTtU',
	},
	{
		'gate': '',
		'brewery': 'BrewDog',
		'beerName': 'Double Hazy',
		'type': 'NEIPA',
		'abv': 7.2,
		'ibu': 30,
		'untapped': 3.84,
		'price': 18,
		'cost': 10.23,
		'supplier': 'Hacerem',
		'_id': 'pqjH92jfoyOmK2P',
	},
	{
		'gate': '',
		'brewery': 'Siren',
		'beerName': 'Pompelmocell o',
		'type': 'Juicy Sour IPA',
		'abv': 6,
		'ibu': '',
		'untapped': 3.64,
		'price': 28,
		'cost': 16,
		'supplier': 'Redax',
		'_id': 'OYPzurfgr3E9IOl',
	},
	{
		'gate': '',
		'brewery': 'Mikkeller',
		'beerName': 'Passion Pool',
		'type': 'Sour Fruited Gose ',
		'abv': 4.6,
		'ibu': 5,
		'untapped': 3.84,
		'price': 20,
		'cost': 11.22,
		'supplier': 'Hacerem',
		'_id': '37YuB68HcHmvSw2',
	},
	{
		'gate': '',
		'brewery': 'Thornbridge',
		'beerName': 'Pride of thy Father ',
		'type': 'NEIPA ',
		'abv': 6,
		'ibu': '',
		'untapped': 3.82,
		'price': 20,
		'cost': 12.25,
		'supplier': 'Ptoyrty',
		'_id': 'J5LmXY0zani5XXn',
	},
]

var gBeers = _loadBeers()

function query(filterBy) {
	let beersToReturn = gBeers
	// console.log('gBeers:', gBeers)
	if (filterBy) {
		var {type, brewery, beerName, minPrice, maxPrice} = filterBy
		maxPrice = maxPrice || Infinity
		minPrice = minPrice || 0
		beersToReturn = gBeers.filter(
			(beer) =>
				beer.type.toLowerCase().includes(type.toLowerCase()) &&
				beer.beerName.toLowerCase().includes(beerName.toLowerCase()) &&
				beer.brewery.toLowerCase().includes(brewery.toLowerCase()) &&
				beer.price < maxPrice &&
				beer.price > minPrice
		)
		// console.log('beersToReturn:', beersToReturn)
	}
	return Promise.resolve([...beersToReturn])
}
function tryBeer(id) {
	const beer = gBeers.find((beer) => beer._id === id)
	return Promise.resolve()
}
function getById(id) {
	const beer = gBeers.find((beer) => beer._id === id)
	return Promise.resolve({...beer})
}

function remove(id) {
	const idx = gBeers.findIndex((beer) => beer._id === id)
	gBeers.splice(idx, 1)
	if (!gBeers.length) gBeers = gDefaultBeers.slice()
	storageService.store(STORAGE_KEY, gBeers)
	return Promise.resolve()
}

function save(beerToSave) {
	if (beerToSave._id) {
		const idx = gBeers.findIndex((beer) => beer._id === beerToSave._id)
		gBeers.splice(idx, 1, beerToSave)
	} else {
		beerToSave._id = makeId()
		gBeers.push(beerToSave)
	}
	storageService.store(STORAGE_KEY, gBeers)
	return Promise.resolve(beerToSave)
}

function getEmptyBeer() {
	return {
		gate: '',
		brewery: '',
		beerName: '',
		type: '',
		abv: '',
		ibu: '',
		untapped: '',
		price: '',
		cost: '',
	}
}

function _loadBeers() {
	let beers = storageService.load(STORAGE_KEY)
	if (!beers || !beers.length) beers = gDefaultBeers
	storageService.store(STORAGE_KEY, beers)
	console.log(beers)
	return beers
}
